version: '3.8'

services:
  development:
    container_name: boilerplate_dev
    image: boilerplate-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  production:
    container_name: boilerplate_prod
    image: boilerplate-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
